### ISSUE TITLE
Improve formatting when using media queries

### ISSUE THREAD

**Issue by gcotelli** [gcotelli/RenoirSt#2]
Improve the general CSS formatting when using media queries. The rules inside the media query section aren't indented making more difficult to determine visually the media rule ending.
Current output:

``` css
@media print
{
h1.ouch
{
  color: red;
}
}
```

Desired output:

``` css
@media print
{
  h1.ouch
  {
    color: red;
  }
}
```
