### ISSUE TITLE
Create mathematical expressions without a hard reference to CssMathExpression

### ISSUE THREAD

**Issue by DamienCassou** [gcotelli/RenoirSt#52]
Currently, you can write something like:

```smalltalk
style margin: (CssMathExpression on: 2 pc) / 3 + 2 percent
```

to generate

```css
{
    margin: calc(2pc / 3 + 2%);
}
```

Why not allowing the following more concise form?

```smalltalk
style margin: 2 pc / 3 + 2 percent
```
